### PR TITLE
add installation of environment-modules to allow usage of aliModules

### PR DESCRIPTION
**Pull request by qgp**
I added the installation of environment-modules for the SLC 5/6 and CC 7 builders, as a new RUN command at the end in order not to invalidate the previous stages.

### CODE REVIEW

**Comment by ktf** [comment]
This cannot be merged anymore, can you please rebase?

**Comment by qgp** [comment]
rebased and and force-pushed to my branch, should be mergeable now

**Comment by ktf** [comment]
Indeed it is. As we need to regenerate images for this and I'm currently away, unless @dberzano wants to do it, it will have to wait until next week.

**Comment by qgp** [comment]
not super-urgent from my side, I updated the containers locally and can work with those, so next week wouldn't be a problem at all

**Comment by dberzano** [comment]
Done, all `:latest` containers on Docker Hub have environment-modules.

**Comment by qgp** [comment]
Thanks a lot, pulling them now ...

**Pull request closed without merging**
