### PR TITLE
Add workaround for EOL centos7 repos

### PR DESCRIPTION
**Pull request by singiamtel**

### CODE REVIEW

**Comment by jackal1-66** [comment]
Ciao @ktf, would you be able to merge these changes?

**Comment by ktf** [comment]
Done. However @singiamtel will have to publish a new container.

**Comment by singiamtel** [comment]
> Done. However @singiamtel will have to publish a new container.

Could you give me access to run https://github.com/alisw/docks/actions/workflows/push-docker-image.yml? I don't have the docker credentials to push it from local

**Comment by jackal1-66** [comment]
@singiamtel please let me know when you have news about this operation

**Pull request merged**
