### PR TITLE
Add Pyyaml to SLC7 DAQ

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@ktf q.e.d. :-)

**Comment by ktf** [comment]
We should really do either `pip install alibuild` or:

```
git clone https://github.com/alisw/alibuild
cd alibuild
pip install -e .
```

in the build scripts.

**Comment by dberzano** [comment]
@kft yes you're right, I would rather use a more complex command too, for instance:

```
pip install git+https://github.com/alisw/alibuild@next --target /current/work/dir/python
```

and then I would export `PATH` and `PYTHONPATH` accordingly. The reason is that we re-use the same container and therefore we don't want to install aliBuild container-wide, since in many cases we want to test different versions. What do you think?

Say, for compatibility, I would merge this PR in any case.

**Comment by ktf** [comment]
I guess you need:

```
rm /current/work/dir/python
pip install git+https://github.com/alisw/alibuild@next --target /current/work/dir/python
```

right? /current/work/dir/python would also be there if the container is recycled, no?

**Comment by dberzano** [comment]
So I have made some tests and research. Unfortunately `--target` is not an optimal solution as it does not copy binaries to the destination. The only reliable solution is using `PYTHONUSERBASE`:

```
ALIBUILD_REPO=alisw
ALIBUILD_BRANCH=next
export PYTHONUSERBASE=`mktemp -d`
export PATH=$PYTHONUSERBASE/bin:$PATH
pip install git+https://github.com/$ALIBUILD_REPO/alibuild@$ALIBUILD_BRANCH --user
```

and then `aliBuild` will work flawlessly. With `PYTHONUSERBASE`, `PYTHONPATH` is not needed. I have tested it on our slc5, 6, 7, and 7-daq.

**Comment by dberzano** [comment]
(Anyway the comment on removing the old wd is correct, this is what we do already with aliBuild cloned from GitHub in the Jenkinsfiles.)

**Comment by ktf** [comment]
fine with me if (monday) we change them like you suggest.

**Comment by dberzano** [comment]
:+1:

**Pull request merged**
