### PR TITLE
Add python2

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by aphecetche** [comment]
@kft probably a naive question : but why do we need python2 for a future system, i.e. which part of our stack is not python3 ready already ?

**Comment by ktf** [comment]
The version of aurora we use and to be consistent with what happens on slc7. I want to get the builder done and then we cleanup.

**Comment by ktf** [comment]
and on slc6

**Comment by aphecetche** [comment]
ok, thanks, fair enough

**Pull request merged**
